/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        FizzBuzzEngine fizzBuzzEngine = new FizzBuzzEngine();

        // STDINから値を受け取り、FizzBuzzをSTDOUTに出力する。Ctl + Cで終了
        java.util.Scanner scanner = new java.util.Scanner(System.in);
        while (scanner.hasNext()) {
            int value = scanner.nextInt();
            System.out.println(fizzBuzzEngine.execute(value));
        }
    }
}
